language: go

go:
  - 1.11.x
  - tip

install: true

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get github.com/fzipp/gocyclo

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - staticcheck ./...
  - gocyclo -over 19 $GO_FILES

after_success:
  - bash <(curl -s https://codecov.io/bash)
