language: go

go:
  - 1.10.x
  - release
  - tip

install: true

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /testing/)
  - go get github.com/golang/lint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 15 $GO_FILES
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)
